INSERT INTO promotions (
  id,
  name,
  description,
  discount_type,
  discount_value,
  maximum_discount,
  minimum_subtotal,
  priority,
  stack_with_coupons,
  is_active,
  valid_from,
  valid_until,
  created_at,
  updated_at
) VALUES (
  'c8aaae87-465c-42e7-9be7-40edbb93bdba',
  'Black Friday 2026',
  'Automatic Black Friday promotion. Review the values before activation.',
  'percentage',
  20.00,
  10000.00,
  20000.00,
  100,
  FALSE,
  FALSE,
  '2026-11-27T00:00:00+01:00',
  '2026-11-28T00:00:00+01:00',
  NOW(),
  NOW()
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  discount_type = EXCLUDED.discount_type,
  discount_value = EXCLUDED.discount_value,
  maximum_discount = EXCLUDED.maximum_discount,
  minimum_subtotal = EXCLUDED.minimum_subtotal,
  priority = EXCLUDED.priority,
  stack_with_coupons = EXCLUDED.stack_with_coupons,
  is_active = EXCLUDED.is_active,
  valid_from = EXCLUDED.valid_from,
  valid_until = EXCLUDED.valid_until,
  updated_at = NOW();
